# Generated by Django 3.0.5 on 2020-04-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/loading.png', upload_to=''),
        ),
    ]
