# Generated by Django 3.0.5 on 2020-04-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200423_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='loading.png', upload_to='product_images'),
        ),
    ]
