# Generated by Django 3.0.5 on 2020-04-24 03:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0008_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='Wishlist',
        ),
    ]
